import type { SharedState, ThemeMode, WorkspaceMode, Scenario, PrepaymentEntry } from "./state";

export type WorkspaceAction =
  | { type: "UPDATE_AMOUNT"; payload: number }
  | { type: "UPDATE_RATE"; payload: number }
  | { type: "UPDATE_TENURE"; payload: number }
  | { type: "RESET_CALCULATOR" }
  | { type: "SWITCH_THEME"; payload: ThemeMode }
  | { type: "SET_MODE"; payload: WorkspaceMode }
  // The full, caller-built entity travels in the payload — see the note
  // on ADD_PREPAYMENT below for why the reducer never generates IDs itself.
  | { type: "ADD_SCENARIO"; payload: Scenario }
  | { type: "REMOVE_SCENARIO"; payload: { id: string } }
  | {
      type: "UPDATE_SCENARIO";
      payload: { id: string; field: "amount" | "rate" | "tenure"; value: number };
    }
  // payload.id is generated by the caller (lib/sync/ids.ts) BEFORE
  // dispatch, not inside the reducer. The reducer is replayed
  // independently on every tab from the *same action* — if it minted its
  // own random id, every tab would compute a different id for "the same"
  // entry, and a later REMOVE_PREPAYMENT by id would silently fail to
  // apply on peers. A reducer must be a pure function of (state, action);
  // this was caught by tests/live-sync-check.ts running the real
  // BroadcastChannel API across two independent reducer instances.
  | { type: "ADD_PREPAYMENT"; payload: PrepaymentEntry }
  | { type: "REMOVE_PREPAYMENT"; payload: { id: string } }
  | { type: "CLEAR_PREPAYMENTS" }
  | { type: "UNDO" }
  // Local-only: applied when a SYNC_INIT snapshot arrives. Never re-broadcast
  // as a DISPATCH_ACTION — see WorkspaceProvider.
  | { type: "HYDRATE_STATE"; payload: SharedState };

/** Actions that represent a deliberate user edit and should therefore be
 *  pushed onto the undo stack before being applied. */
export const UNDOABLE_TYPES = new Set<WorkspaceAction["type"]>([
  "UPDATE_AMOUNT",
  "UPDATE_RATE",
  "UPDATE_TENURE",
  "RESET_CALCULATOR",
  "SWITCH_THEME",
  "SET_MODE",
  "ADD_SCENARIO",
  "REMOVE_SCENARIO",
  "UPDATE_SCENARIO",
  "ADD_PREPAYMENT",
  "REMOVE_PREPAYMENT",
  "CLEAR_PREPAYMENTS",
]);
